////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////
// Project Name:
// Description:
// Author: Warren Gates (aka HERMITJS)
// Website:
// Support: teamkhonsu@gmail.com
// Twitter: http://twitter.com/VVarrenTV
// Contributers [Name <email> <github>;]: Warren Gates warrenckhan@gmail.com TheHermitKhan;
////////////////////////////////////////////////////////////
/////////////////// DO NOT EDIT THIS FILE //////////////////
////////////////////////////////////////////////////////////
//RUN OUR JQUERY

$(document).ready(function(){

//STREAM INFO AND STATUS API CALL
  var twitchUserName = ['SniperNamedG','CMStarke','MewtwoRaves','DarkAcreJack','sideshowmatt','blackdynamitetv','johanmoney','sblindside','vvarrentv',"thenutzxd",'jamaica105','michiganspartan','ritterriffic','injectusdoll'];
  // //Iterate through the array of usernames and call getTwitch
  twitchUserName.forEach(function(name) {
    getTwitch(name)
  });

  $(".card").click(function() {
		var status = $(this).attr('class');
		if (status === "cardFeature") {
			$(".online, .offline").show();
      $("#all-streams").addClass("active");
      $("#online, #offline").removeClass("active");
		} else if (status === "online") {
			$(".online").show();
			$(".offline").hide();
      $("#online").addClass("active");
      $("#all-streams, #offline").removeClass("active");
		} else {
			$(".offline").show();
			$(".online").hide();
      $("#offline").addClass("active");
      $("#all-streams, #online").removeClass("active");
		}
	});

});
function getTwitch(twitchUserName){
   console.log(twitchUserName);
  $.ajax({
    type:"GET",
    url:"https://api.twitch.tv/kraken/streams/" + twitchUserName,
    headers:{
      'Client-ID': 'dhtxhmg8vey6qz5y964c3u15vmcssa'
    },
    success: function twitchData(data) {
      // Call 'streams' and if the channel is active, get stream data
      if(data.stream !== null){

        var streamImage = data.stream.preview.large;
        var streamGame = data.stream.game;
        var streamInfo = data.stream.channel.status;
        var streamLogo = data.stream.channel.logo;
        var streamFollowers = data.stream.channel.followers;
        var streamURL = data.stream.channel.url;
        var defaultImage = 'https://media.giphy.com/media/26FKZH3iV19wR7uYE/source.gif';
          console.log(twitchUserName);
        //IF EVERYTHING IS A SUCCESS IT BUILDS A STREAMCARD//
          if (streamLogo !== null){
            streamCard = "<a  target='myiframe' href='https://player.twitch.tv/?channel="+twitchUserName+"'><div class='card cardList cardFeature'><span class='tag tag-success status-bar'>ONLINE</span><img class='round-logo img-responsive logo' src='" + streamLogo + "' alt='" + twitchUserName + "logo'><div class='text-padding'><h4 class='twitch_channel_name'>" + twitchUserName.toUpperCase() + "</h4><p><strong>" + streamGame.toUpperCase() + ": </strong>" + streamInfo.toUpperCase() + "</p><p>" + streamFollowers +"</p></div></div></a>";
            console.log(twitchUserName);
            $(".card-container").append(streamCard);
          } else{
            streamCard = "<a  target='myiframe' href='https://player.twitch.tv/?channel="+twitchUserName+"'><div class='card cardList cardFeature'><span class='tag tag-success status-bar'>ONLINE</span><img class='round-logo img-responsive logo' src='" + defaultImage + "' alt='" + twitchUserName + "logo'><div class='text-padding'><h4 class='twitch_channel_name'>" + twitchUserName.toUpperCase() + "</h4><p><strong>" + streamGame.toUpperCase() + ": </strong>" + streamInfo.toUpperCase() + "</p><p>" + streamFollowers +"</p></div></div></a>";
            console.log(twitchUserName);
            $(".card-container").append(streamCard);
          }
      } else {
        // If the channel is offline, get channel data
        $.ajax({
          type:"GET",
          url:"https://api.twitch.tv/kraken/channels/" + twitchUserName,
          headers:{
            'Client-ID': 'dhtxhmg8vey6qz5y964c3u15vmcssa'
          },
          success: function(data){
            var streamBanner = data.video_banner;
            var streamLogo = data.logo;
            var streamError = data.status;
            var streamURL = data.stream.channel.url;
            var streamCard = " ";
            console.log(twitchUserName);
            //IF THERE IS NO CHANNEL INFO
            if (streamError == 404 || streamBanner == null || streamLogo == null){
              $.ajax({
                type:"GET",
                url:"https://api.twitch.tv/kraken/users/" + twitchUserName,
                headers:{
                  'Client-ID': 'dhtxhmg8vey6qz5y964c3u15vmcssa'
      },
                success: function(data){

                  var streamMessage = data.error;

                  var defaultImage = "https://media.giphy.com/media/EZJIg5PUjdDKU/giphy.gif";
                  var defaultThumb = "https://media.giphy.com/media/l3q31122uBsO7hpmw/source.gif";
                  console.log(twitchUserName);
                  //IF ACCOUNT HAS BEEN CLOSED BUILD STREAMCARD
                  if(streamMessage == "Unprocessable Entity"){
                    streamCard = "<a  target='myiframe' href='https://player.twitch.tv/?channel="+twitchUserName+"'><div class='card '><span class='tag tag-success status-bar'>OffLINE</span><img class='round-logo img-responsive logo' src='" + defaultImage + "' alt='" + twitchUserName + "logo'><div class='text-padding'><h4 class='twitch_channel_name'>" + twitchUserName.toUpperCase() + "</h4><p><strong>" + streamGame.toUpperCase() + ": </strong>" + streamInfo.toUpperCase() + "</p><p>" + streamFollowers +"</p></div></div></a>";
                    $(".card-container").append(streamCard);
                    console.log(twitchUserName);
                  } else if (streamMessage == "Not Found"){
                    //IF IT NEVER EXISTED
                    streamCard = "<a  target='myiframe' href='https://player.twitch.tv/?channel="+twitchUserName+"'><div class='card '><span class='tag tag-success status-bar'>OffLINE</span><img class='round-logo img-responsive logo' src='" + defaultImage + "' alt='" + twitchUserName + "logo'><div class='text-padding'><h4 class='twitch_channel_name'>" + twitchUserName.toUpperCase() + "</h4><p><strong>" + streamGame.toUpperCase() + ": </strong>" + streamInfo.toUpperCase() + "</p><p>" + streamFollowers +"</p></div></div></a>";
                    console.log(twitchUserName);
                    $(".card-container").append(streamCard);
                  }else if (streamBanner == null && streamLogo == null){
                    //IF Banner AND  Logo don't Work
                    streamCard = "<a  target='myiframe' href='https://player.twitch.tv/?channel="+twitchUserName+"'><div class='card '><span class='tag tag-success status-bar'>OffLINE</span><img class='round-logo img-responsive logo' src='" + defaultImage + "' alt='" + twitchUserName + "logo'><div class='text-padding'><h4 class='twitch_channel_name'>" + twitchUserName.toUpperCase() + "</h4><p><strong>" + streamGame.toUpperCase() + ": </strong>" + streamInfo.toUpperCase() + "</p><p>" + streamFollowers +"</p></div></div></a>";
                    console.log(twitchUserName);
                    $(".card-container").append(streamCard);
                  } else if (streamBanner == null){
                    //IF Banner Doesn't Exist
                    streamCard = "<a  target='myiframe' href='https://player.twitch.tv/?channel="+twitchUserName+"'><div class='card '><span class='tag tag-success status-bar'>OffLINE</span><img class='round-logo img-responsive logo' src='" + defaultImage + "' alt='" + twitchUserName + "logo'><div class='text-padding'><h4 class='twitch_channel_name'>" + twitchUserName.toUpperCase() + "</h4><p><strong>" + streamGame.toUpperCase() + ": </strong>" + streamInfo.toUpperCase() + "</p><p>" + streamFollowers +"</p></div></div></a>";
                    console.log(twitchUserName);
                    $(".card-container").append(streamCard);
                  }
                }
              })
            } else { // If account exists, but user is not currently streaming, build streamCard
              streamCard = "<a target='myiframe' href='https://player.twitch.tv/?channel="+twitchUserName+"'><div class='card '><span class='tag tag-success status-bar'>OffLINE</span><img class='round-logo img-responsive logo' src='" + defaultImage + "' alt='" + twitchUserName + "logo'><div class='text-padding'><h4 class='twitch_channel_name'>" + twitchUserName.toUpperCase() + "</h4><p><strong>" + streamGame.toUpperCase() + ": </strong>" + streamInfo.toUpperCase() + "</p><p>" + streamFollowers +"</p></div></div></a>";
              console.log(twitchUserName);
              $(".card-container").append(streamCard);
            }
          }
        })
      }
    }
  })
}
